### ISSUE TITLE
Misalignment in cast after allocation for ARM gcc

### ISSUE THREAD

**Issue by dgreatwood** [dwd/rapidxml#13]
At least one cast (and possible others) will cause "increases required alignment of target type [-Werror=cast-alig]" when compiling on ARM/RaspberryPi.
I saw the error in line 672: header *new_header = reinterpret_cast<header *>(pool);

With gcc, I change to:
                // __builtin_assume_aligned is a GCC directive; this paper -    
                // http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0886r0.pdf                                                                         
                // - outlines the directives for some other compilers. Looks    
                // like we can use std::assume_aligned from C++2020 onwards:    
                //   https://en.cppreference.com/w/cpp/memory/assume_aligned    
		header *new_header = reinterpret_cast<header *>(__builtin_assume_aligned(pool, RAPIDXML_ALIGNMENT));

That made my code compile.

I imagine there may be other places where  __builtin_assume_aligned is needed in rapidxml.hpp

**Comment by dwd** [comment]
Yet another ancient issue I'm finally getting to.

So... Yes, the entire allocator in rapidxml was written assuming a fairly simplistic alignment model. This probably works fine on x86/amd64, but not on ARM. std::assume_aligned might fix, or might cause undefined behaviour, depending.

The correct model (as from C++11ish) is to use alignof and std::align to shift the pointers for alignment depending on the alignment of the type itself, which can vary (and I think does on ARM).

Working on this on the v2 branch. Interesting rabbit hole.

**Comment by dgreatwood** [comment]
Thanks for going back to this. As you rightly say, it would be wrong ("undefined") to use an "assume" if the assumption may be false...

FYI, I believe the specific Pi that I was using was: Raspberry Pi 3 - Model B+ - 1.4GHz Cortex-A53 with 1GB RAM.
Per a quick search that uses a CPU: Broadcom BCM2837B0, Cortex-A53 (ARMv8) 64-bit SoC @ 1.4GHz
I don't know why that would align differently to a 64-bit x86, but of course it might.

The OS would have been Ubuntu. Could have been v18.04 or 18.10.

Good luck with the work.

**Comment by dwd** [comment]
Well, I've not got anything to test this on, but it now works (again) on amd64, and is using the C++11 alignment stuff, which I assume will make it portable.

**Comment by dwd** [comment]
Righty, that's v2 released. I'll assume this issue is closed in as much as I think I've done what's needed.
